add

diff --git a/InstallDependencies b/InstallDependencies
--- a/InstallDependencies
+++ b/InstallDependencies
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# 检查是否已安装 Homebrew
 if command -v brew &>/dev/null; then
     echo "Homebrew installed."
 else
@@ -8,34 +9,76 @@ else
         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
         echo "Homebrew installed successfully."
     else
-        echo "This script only supports macOS" >&2
+        echo "This script only supports macOS." >&2
         exit 1
     fi
 fi
 
+# 安装 rbenv
 
-tap="viabtc/coinex"
-cocoapods_version="1.11.3"
-fastlane_version="2.212.1"
-
-if ! brew tap | grep -q "^${tap}$"; then
-echo "${tap} tap not found, adding it now..."
-brew tap-new "${tap}"
-fi
-
-if brew search "cocoapods@${cocoapods_version}" | grep -q "cocoapods@${cocoapods_version}"; then
-echo "cocoapods@${cocoapods_version} exists"
+if ! command -v rbenv > /dev/null 2>&1; then
+  echo "rbenv is not installed, installing now..."
+  
+  brew install rbenv ruby-build
+  
+  # Add rbenv to PATH and initialize it
+  echo '\n# 设置rbenv\neval "$(rbenv init - zsh)"' >> ~/.zshrc
+  
+  source ~/.zshrc
+  
+  echo "rbenv installed successfully."
 else
-brew extract --version="${cocoapods_version}" cocoapods "${tap}"
+  echo "rbenv is already installed."
 fi
 
-if brew search "fastlane@${fastlane_version}" | grep -q "fastlane@${fastlane_version}"; then
-echo "fastlane@${fastlane_version} exists"
+
+# 安装 ruby
+desired_ruby_version="3.1.3"
+
+# Check if rbenv is installed
+if ! command -v rbenv > /dev/null 2>&1; then
+  echo "rbenv is not installed. Please install rbenv first."
+  exit 1
+fi
+
+if ! rbenv versions --bare | grep -q "^${desired_ruby_version}\$"; then
+  echo "Ruby version ${desired_ruby_version} is not installed, installing now..."
+  
+  rbenv install "${desired_ruby_version}"
+  
+  echo "Ruby version ${desired_ruby_version} installed successfully."
 else
-brew extract --version="${fastlane_version}" fastlane "${tap}"
+  echo "Ruby version ${desired_ruby_version} is already installed."
 fi
 
-brew reinstall cocoapods@${cocoapods_version}
-brew link --overwrite cocoapods@${cocoapods_version}
-brew reinstall fastlane@${fastlane_version}
-brew link --overwrite fastlane@${fastlane_version}
+# 查看ruby安装版本
+ruby -v
+
+###### 安装bundler
+
+# Check if bundler is installed
+if ! gem list bundler -i > /dev/null; then
+  echo "Bundler not installed. Installing Bundler..."
+  gem install bundler
+  echo "Bundler installed successfully."
+else
+  echo "Bundler is already installed."
+fi
+
+# Check if Gemfile exists in the current directory
+if [ -f "Gemfile" ]; then
+  echo "Gemfile found, installing gems using Bundler..."
+  
+  # Install gems listed in Gemfile using Bundler
+  bundle install
+  
+  echo "Gems installed successfully."
+else
+  echo "Gemfile not found in the current directory. Please make sure you have a Gemfile in the current directory."
+fi
+
+bundle exec pod install --verbose
+
+
+
+
