测试

diff --git a/.github/workflows/ios-cd-dev.yml b/.github/workflows/ios-cd-dev.yml
--- a/.github/workflows/ios-cd-dev.yml
+++ b/.github/workflows/ios-cd-dev.yml
@@ -19,25 +19,25 @@ jobs:
           echo "开始执行输出"
           echo "开始执行输出1111"
           echo "开始执行输出1111"
-          # exit 1
-      - name: Notify Slack on Success
-        if: success()
-        uses: ./.github/workflows/slack-notifications.yml
-        with:
-          status: 'success'
-          success_message_title: '✅ CoinEx iOS 打包成功，已上传到服务器'
-          pr_html_url: ${{ github.event.pull_request.html_url }}
-          pr_number: ${{ github.event.pull_request.number }}
-          pr_title: ${{ github.event.pull_request.title }}
-          pr_body: ${{ github.event.pull_request.body }}
-          base_sha: ${{ github.event.pull_request.base.sha }}
-          head_sha: ${{ github.event.pull_request.head.sha }}
+          exit 1
+      # - name: Notify Slack on Success
+      #   if: success()
+      #   uses: ./.github/workflows/slack-notifications.yml
+      #   with:
+      #     status: 'success'
+      #     success_message_title: '✅ CoinEx iOS 打包成功，已上传到服务器'
+      #     pr_html_url: ${{ github.event.pull_request.html_url }}
+      #     pr_number: ${{ github.event.pull_request.number }}
+      #     pr_title: ${{ github.event.pull_request.title }}
+      #     pr_body: ${{ github.event.pull_request.body }}
+      #     base_sha: ${{ github.event.pull_request.base.sha }}
+      #     head_sha: ${{ github.event.pull_request.head.sha }}
       - name: Notify Slack on Failure
         if: failure()
         uses: ./.github/workflows/slack-notifications.yml
         with:
           status: 'failure'
-          failure_message_title: '❌ CoinEx iOS 打包失败，请查看运行错误'
+          # failure_message_title: '❌ CoinEx iOS 打包失败，请查看运行错误'
         
       # - name: Notify Slack on Success
       #   if: success()
